package com.eBilling.baseModel;

import java.util.List;

/**
 *
 * @author autogenerated
 */

public class LoginBaseInfo {
	protected String password;
	protected String name;
	protected String loginId;
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	

}